{{- if .Values.ingress.enable }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reportportal-gateway-ingress
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{ if .Values.ingress.usedomainname }}
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: ui-0
          servicePort: headless
      - path: /ui/?(.*)
        backend:
          serviceName: ui-0
          servicePort: headless
      - path: /uat/?(.*)
        backend:
          serviceName: uat-0
          servicePort: headless
  {{- end -}}
{{ else }}
  - http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: ui-0
          servicePort: headless
      - path: /ui/?(.*)
        backend:
          serviceName: ui-0
          servicePort: headless
      - path: /uat/?(.*)
        backend:
          serviceName: uat-0
          servicePort: headless
{{ end }}
status:
  loadBalancer: {}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}