apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
        - name: RP_MONGO_URI
          value: mongodb://mongouser:mongouser123@mongodb-rp:27017/reportportal?authSource=reportportal123
        - name: RP_PROFILES
          value: docker
        image: reportportal/service-api:4.3.4
        name: api
        resources: {}
      restartPolicy: Always
status: {}
