apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - args:
        - --consulcatalog.endpoint=registry:8500
        - --defaultEntryPoints=http
        - --entryPoints=Name:http Address::8080
        - --logLevel=DEBUG
        - --web
        - --web.address=:8081
        image: traefik:1.6.3
        name: gateway
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
