apiVersion: v1
kind: Service
metadata:
  name: registry
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: "8500"
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    component: reportportal-registry
  type: ClusterIP
