# dependencies:
#   - name: mongodb
#     version: 0.4.18
#     repository: https://kubernetes-charts.storage.googleapis.com/
#     condition: mongodb.installdep.enable
#   - name: elasticsearch
#     version: 1.17.0
#     repository: https://kubernetes-charts.storage.googleapis.com/
#     condition: elasticsearch.installdep.enable
