# docker registry in which the images are hosted
registry: "" # docker-registry.com

# list of images

traefik:
  repository: gcr.io/kcluster-225309/traefik
  tag: 1.7.6
  # gcr.io/kcluster-225309/traefik:1.7.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

serviceindex:
  repository: gcr.io/kcluster-225309/service-index
  tag: 4.2.0
  # gcr.io/kcluster-225309/service-index:4.2.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
consul:
  repository: gcr.io/kcluster-225309/consul
  tag: 1.0.6
  # gcr.io/kcluster-225309/consul:1.0.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
serviceauthorization:
  repository: gcr.io/kcluster-225309/service-authorization
  tag: 4.2.0
  # gcr.io/kcluster-225309/service-authorization:4.2.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  sessionLiveTime: 86400
serviceui:
  repository: gcr.io/kcluster-225309/service-ui
  tag: 4.3.6
  # gcr.io/kcluster-225309/service-ui:4.3.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
serviceanalyzer:
  repository: gcr.io/kcluster-225309/service-analyzer
  tag: 4.3.0
  # gcr.io/kcluster-225309/service-analyzer:4.3.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
serviceapi:
  repository: gcr.io/kcluster-225309/service-api
  tag: 4.3.4
  # gcr.io/kcluster-225309/service-api:4.3.4
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 1000Mi
    limits:
      cpu: 300m
      memory: 1500Mi
jira:
  repository: gcr.io/kcluster-225309/service-jira
  tag:     4.3.0
  # gcr.io/kcluster-225309/service-jira:4.3.0
  restart: always
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 1000Mi
    limits:
      cpu: 300m
      memory: 1500Mi
elasticsearch:
  installdep:
    enable: false
  endpoint:
    external: true
    address: elasticsearch-client
    port: 9200
mongodb:
  installdep:
    enable: false
  endpoint: 
    external: true
    address: "mongodb"
    port: 27017
    username: "rpuser"
    dbname: "reportportal"

mongoSecretName: "mongodb-password"

# ingress configuration for the ui
# If you have installed ingress controller and want to expose application - set INGRESS.ENABLE to true.
# If you have some domain name set INGRESS.USEDOMAINNAME variable to true and set this fqdn to INGRESS.HOSTS
# If you don't have any domain names - set INGRESS.USEDOMAINNAME to false
ingress:
  enable: true
  # IF YOU HAVE SOME DOMAIN NAME SET INGRESS.USEDOMAINNAME to true
  usedomainname: false
  hosts:
    - reportportal.k8.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true

# persistence configuration for elasticsearch, mongodb & consul
persistence:
  registry:
    enabled: true
    ## If true will use an existing PVC instead of creating one
    # useExisting: false
    spec:
      ## consul data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      capacity:
        storage: 10Gi
